### ISSUE TITLE
[Feature Request / Spec] Adding TiDB specific resources

### ISSUE THREAD

**Issue by zph** [petoju/terraform-provider-mysql#159]
👋 Hi @petoju,

First off, thank you for the work you've put into maintaining this.

After contributing PR #158 and seeing that there are already files referencing TiDB, I'm wondering what your plans/design is for the project with regard to further extensions that support TiDB?

Specifically, I'm considering how to add and manage TiDB's Resource Controls and they're closely integrated with mysql users in TiDB. Resource Controls are declared via SQL and they're like dynamodb's Read Capacity Units or Write Capacity Units and allow for multi-tenancy of users while maintaining quality of service. [link](https://docs.pingcap.com/tidb/stable/tidb-resource-control)

Is that something you're interested to have contributed back to this project or do you prefer it live elsewhere?

**Comment by petoju** [comment]
Hi @zph,

> I'm wondering what your plans/design is for the project with regard to further extensions that support TiDB?

I have no plans at all. I'm maintaining this provider in my free time and my goal is working MySQL.
TiDB support is "best effort" - I don't really understand it, but I'm trying to keep it working as someone requested it.

> Is that something you're interested to have contributed back to this project or do you prefer it live elsewhere?

I don't have strong opinions here. TiDB was added because someone didn't want to support own MySQL provider fork or alternative. If something is tested and doesn't break other code, I'm fine with merging it.

I can say I won't be here for large part of July, so if you are under time pressure, custom fork or alternative provider is the way to go.

**Comment by zph** [comment]
@petoju Ok, thank you.

I think it's best for the community to contribute back to this as a main provider but I also know I'll want to contribute changes in July.

My plan is to upstream everything that I can back to here with testing/compatibility with other flavors of mysql and I'll keep a fork where I can move ahead temporarily while we agree on patches 👍
